pipeline {
    agent any

    environment {
        PASS = credentials('DOCKER_HUB_PASS')
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                    ./pipeline6/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./pipeline6/jenkins/build/build.sh
                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'pipeline6/java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            steps {
                sh './pipeline6/jenkins/test/mvn.sh mvn test'
            }

            post {
                always {
                    junit 'pipeline6/java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Push') {
            steps {
                sh './pipeline6/jenkins/push/push.sh'
            }
        }
    }
}
