pipeline {
    //agent none
    agent any

    stages {
        stage('Build') {
            //agent {label 'mynode2'}
            steps {
                sh '''
                    ./pipeline6/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./pipeline6/jenkins/build/build.sh
                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'pipeline6/java-app/target/*.jar', fingerprint: true
                }
            }
        }
    }
}
